name: Build and Run Application on Linux

on:
  workflow_dispatch:

jobs:
  run:
    runs-on: [self-hosted, Linux, X64, xaf-load-testing]
    timeout-minutes: 40
    env:
      CONNECTION_STRING: MySqlConnectionString
    steps:
      - name: Get ip
        run: echo "LOCAL_IP_ADDRESS=$(ip -o route get to 8.8.8.8 | sed -n 's/.*src \([0-9.]\+\).*/\1/p')" >> $GITHUB_ENV
      - name: Show IP
        run: echo ${{ env.LOCAL_IP_ADDRESS }}
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x
      - name: Add DevExpress NuGet Package Source
        if: ${{ always() }}
        run: dotnet nuget add source ${{ secrets.DEVEXPRESS_NUGET_URL }} -n devexpress-nuget
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore
      - name: Update database
        run: dotnet run --project LoadTestingApp.Blazor.Server --updateDatabase --forceUpdate --silent
      - name: Run application
        run: dotnet run --project LoadTestingApp.Blazor.Server &
      - name: Run tests
        uses: aurelien-baudet/workflow-dispatch@v2
        with:
          workflow: Load Testing
          token: ${{ secrets.PERSONAL_TOKEN }}
          wait-for-completion: true
          inputs: '{ "appUrl": "${{ env.LOCAL_IP_ADDRESS }}:5002" }'