name: Build and Run Application

on:
  workflow_dispatch:
    pull_request:
    branches: [ main ]

env:
  VM_MEMORY: 2600
  VM_CPU: 4
  VM_IMAGE: UBUNTU

jobs:
  run:
    runs-on: farm
    timeout-minutes: 20
    env:
      VM_IMAGE: Win
    steps:
      - name: Get ip
        run:  |
          echo "::set-output name={ip}::$(netsh interface ip show address "Ethernet 3" | where { $_ -match 'IP Address'} | %{ $_ -replace '^.*IP Address:\W*', ''})"
        id: get_ip
      - name: Checkout
        uses: ./../../checkout
      # - name: Install SQLite
      #   run: |
      #     sudo apt-get update
      #     sudo apt-get install sqlite3
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x
      - name: Add DevExpress NuGet Package Source
        run: dotnet nuget add source ${{ secrets.DEVEXPRESS_NUGET_URL }}
      - name: Clear NuGet cache
        run: dotnet nuget locals -c all
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore
      - name: Update database
        run: dotnet run --project LoadTestingApp.Blazor.Server --updateDatabase --forceUpdate --silent
      - name: Generate Certificate
        run: dotnet dev-certs https
      # - name: Trust certificate
      #   run: dotnet dev-certs https --trust
      - name: Run application
        run: start dotnet run --project LoadTestingApp.Blazor.Server
        shell: cmd
      - name: Run tests
        uses: aurelien-baudet/workflow-dispatch@v2
        with:
          workflow: Load Testing
          wait-for-completion: true
          inputs: '{ "appUrl": "${{ steps.get_ip.outputs.ip }}" }'