name: Experimental Node App

on:
  workflow_dispatch:

jobs:
  run:
    runs-on: farm
    timeout-minutes: 30
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'
      - name: Install Packages
        run: npm i
      - name: Run Tests
        run: npm run testcafe-test
      # - name: Run application
      #   run: Start-Process -nonewwindow dotnet "run --project LoadTestingApp.Blazor.Server"
      # - name: Install Packages
      #   run: npm i
      # - name: Run Tests
      #   run: node ./tests/index.js localhost 10