name: Experimental Node App

on:
  workflow_dispatch:
    inputs:
      appUrl:
        description: 'Appliation url'  
        required: true
        default: ''

env:
  VM_MEMORY: 2600
  VM_CPU: 4
  VM_IMAGE: UBUNTU

jobs:
  run:
    runs-on: [self-hosted, Windows, X64]
    timeout-minutes: 30
    steps:
      - name: Checkout
        uses: ./../../checkout
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'
      - name: Install Packages
        run: npm i
      - name: Run Tests
        run: npm run testcafe-test