name: Load Testing

on:
  workflow_dispatch:
    inputs:
      appUrl:
        description: 'Appliation url'  
        required: true
        default: ''

env:
  APP_URL: ${{ github.event.inputs.appUrl }}

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        workers: [worker_01, worker_02, worker_03, worker_04, worker_05, worker_06, worker_07, worker_08, worker_09]
      fail-fast: false
    env:
      WORKER_NAME: ${{ matrix.workers }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'
      - name: Install Packages
        run: npm i
      - name: Run Tests
        run: node ./tests/index.js ${{ github.event.inputs.appUrl }} 30
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        if: ${{ always() }}
        with:
          name: screenshots
          path: screenshots