name: Load testing

on:
  workflow_dispatch

env:
  VM_MEMORY: 2600
  VM_CPU: 4
  VM_IMAGE: UBUNTU

jobs:
  run:
    runs-on: farm
    strategy:
      matrix:
        workers: [worker_01, worker_02, worker_03, worker_04, worker_05, worker_06, worker_07, worker_08, worker_09, worker_10]
    env:
      WORKER_NAME: ${{ matrix.workers }}