name: Load Testing

on:
  workflow_dispatch:
    inputs:
      appUrl:
        description: 'Appliation url'  
        required: true
        default: ''

env:
  VM_MEMORY: 3072
  VM_CPU: 4
  VM_IMAGE: UBUNTU
  TESTCAFE_DASHBOARD_URL: https://ddev.testcafe.io
  TESTCAFE_DASHBOARD_TOKEN: ${{ secrets.DASHBOARD_TOKEN }}
  APP_URL: ${{ github.event.inputs.appUrl }}

jobs:
  run:
    runs-on: farm
    strategy:
      matrix:
        workers: [worker_01, worker_02, worker_03]
    env:
      WORKER_NAME: ${{ matrix.workers }}
    steps:
      - name: Checkout
        uses: ./../../checkout
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'
      - name: Install Chrome
        run: |
            wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
            sudo sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list'
            sudo apt-get update
            sudo apt-get install google-chrome-stable
      - name: Install Packages
        run: npm i
      - name: Run Tests
        run: node ./tests/index.js ${{ github.event.inputs.appUrl }} 25
      # - name: Run testcafe tests
      #   run: npx testcafe chrome:headless ./tests/list-view-testcafe-test.js -e -c 10 -s path=screenshots,pathPattern=${TEST_INDEX}/${USERAGENT}/${FILE_INDEX}.png
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        if: ${{ always() }}
        with:
          name: screenshots
          path: screenshots